development:
  adapter: postgresql
  encoding: unicode
  database: development_db
  pool: 5
  username: alexbeam
  password: 3Wolfspoon

test:
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: alexbeam
  password: 3Wolfspoon

production:
  adapter: postgresql
  encoding: unicode
  database: production_db
  pool: 5
  username: alexbeam
  password: 3Wolfspoon