# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

atoms = Atom.create([
  {number: 1, name: 'Hydrogen', shortname: 'H', weight: 1.00794, moe: 7, row_position_x: 1, row_position_y: 1, description: 'lah Blah'}, 
  {number: 2, name: 'Helium', shortname: 'He', weight: 4.002602, moe: 2, row_position_x: 18, row_position_y: 1, description: 'lah Blah'},
  {number: 3, name: 'Lithium', shortname: 'Li', weight: 6.941, moe: 2, row_position_x: 1, row_position_y: 2, description: 'lah Blah'},
  {number: 4, name: 'Beryllium', shortname: 'Be', weight: 9.012182, moe: 3, row_position_x: 2, row_position_y: 2, description: 'lah Blah'},
  {number: 5, name: 'Boron', shortname: 'B', weight: 10.811, moe: 7, row_position_x: 13, row_position_y: 2, description: 'lah Blah'},
  {number: 6, name: 'Carbon', shortname: 'C', weight: 12.0107, moe: 8, row_position_x: 14, row_position_y: 2, description: 'lah Blah'},
  {number: 7, name: 'Nitrogen', shortname: 'N', weight: 14.0067, moe: 2, row_position_x: 15, row_position_y: 2, description: 'lah Blah'},
  {number: 8, name: 'Oxygen', shortname: 'O', weight: 15.9994, moe: 3, row_position_x: 16, row_position_y: 2, description: 'lah Blah'},
  {number: 9, name: 'Fluorine', shortname: 'F', weight: 18.9984032, moe: 5, row_position_x: 17, row_position_y: 2, description: 'lah Blah'},
  {number: 10, name: 'Neon', shortname: 'Ne', weight: 20.1797, moe: 6, row_position_x: 18, row_position_y: 2, description: 'lah Blah'},
  {number: 11, name: 'Sodium', shortname: 'Na', weight: 22.98976, moe: 2, row_position_x: 1, row_position_y: 3, description: 'lah Blah'},
  {number: 12, name: 'Magnesium', shortname: 'Mg', weight: 24.305, moe: 6, row_position_x: 2, row_position_y:3, description: 'lah Blah'},
  {number: 13, name: 'Aluminium', shortname: 'Al', weight: 26.9815386, moe: 8,row_position_x: 13, row_position_y: 3, description: 'lah Blah'},
  {number: 14, name: 'Silicon', shortname: 'Si', weight: 28.0855, moe: 3, row_position_x: 14, row_position_y: 3, description: 'lah Blah'},
  {number: 15, name: 'Phosphorus', shortname: 'P', weight: 30.973762, moe: 2, row_position_x: 15, row_position_y: 3, description: 'lah Blah'},
  {number: 16, name: 'Sulfur', shortname: 'S', weight: 32.065, moe: 5, row_position_x: 16, row_position_y: 3, description: 'lah Blah'},
  {number: 17, name: 'Chlorine', shortname: 'Cl', weight: 35.453, moe: 2, row_position_x: 17, row_position_y: 3, description: 'lah Blah'},
  {number: 18, name: 'Argon', shortname: 'Ar', weight: 39.948, moe: 1, row_position_x: 18, row_position_y: 3, description: 'lah Blah'},
  {number: 19, name: 'Potassium', shortname: 'K', weight: 39.0983, moe: 4, row_position_x: 1, row_position_y: 4, description: 'lah Blah'},
  {number: 20, name: 'Calcium', shortname: 'Ca', weight: 40.078, moe: 6, row_position_x: 2, row_position_y: 4, description: 'lah Blah'},
  {number: 21, name: 'Scandium', shortname: 'Sc', weight: 44.955912, moe: 1, row_position_x: 3, row_position_y: 4, description: 'lah Blah'},
  {number: 22, name: 'Titanium', shortname: 'Ti', weight: 47.867, moe: 1, row_position_x: 4, row_position_y: 4, description: 'lah Blah'},
  {number: 23, name: 'Vanadium', shortname: 'V', weight: 50.9415, moe: 6, row_position_x: 5, row_position_y: 4, description: 'lah Blah'},
  {number: 24, name: 'Chromium', shortname: 'Cr', weight: 51.9961, moe: 5, row_position_x: 6, row_position_y: 4, description: 'lah Blah'},
  {number: 25, name: 'Manganese', shortname: 'Mn', weight: 54.938045, moe: 2, row_position_x: 7, row_position_y: 4, description: 'lah Blah'},
  {number: 26, name: 'Iron', shortname: 'Fe', weight: 55.845, moe: 2, row_position_x: 8, row_position_y: 4, description: 'lah Blah'},
  {number: 27, name: 'Cobalt', shortname: 'Co', weight: 58.933195, moe: 5, row_position_x: 9, row_position_y: 4, description: 'lah Blah'},
  {number: 28, name: 'Nickel', shortname: 'Ni', weight: 58.6934, moe: 2, row_position_x: 10, row_position_y: 4, description: 'lah Blah'},
  {number: 29, name: 'Copper', shortname: 'Cu', weight: 63.546, moe: 3, row_position_x: 11, row_position_y: 4, description: 'lah Blah'},
  {number: 30, name: 'Zinc', shortname: 'Zn', weight: 65.38, moe: 4, row_position_x: 12, row_position_y: 4, description: 'lah Blah'},
  {number: 31, name: 'Gallium', shortname: 'Ga', weight: 69.723, moe: 1, row_position_x: 13, row_position_y: 4, description: 'lah Blah'},
  {number: 32, name: 'Germanium', shortname: 'Ge', weight: 72.63, moe: 1, row_position_x: 14, row_position_y: 4, description: 'lah Blah'},
  {number: 33, name: 'Arsenic', shortname: 'As', weight: 74.9216, moe: 2, row_position_x: 15, row_position_y: 4, description: 'lah Blah'},
  {number: 34, name: 'Selenium', shortname: 'Se', weight: 78.96, moe: 3, row_position_x: 16, row_position_y: 4, description: 'lah Blah'},
  {number: 35, name: 'Bromine', shortname: 'Br', weight: 79.904, moe: 1, row_position_x: 17, row_position_y: 4, description: 'lah Blah'},
  {number: 36, name: 'Krypton', shortname: 'Kr', weight: 83.798, moe: 2, row_position_x: 18, row_position_y: 4, description: 'lah Blah'},
  {number: 37, name: 'Rubidium', shortname: 'Rb', weight: 85.4678, moe: 3, row_position_x: 1, row_position_y: 5, description: 'lah Blah'},
  {number: 38, name: 'Strontium', shortname: 'Sr', weight: 87.62, moe: 1, row_position_x: 2, row_position_y:5, description: 'lah Blah'},
  {number: 39, name: 'Yttrium', shortname: 'Y', weight: 88.90585, moe: 2, row_position_x: 3, row_position_y: 5, description: 'lah Blah'},
  {number: 40, name: 'Zirconium', shortname: 'Zr', weight: 91.224, moe: 2, row_position_x: 4, row_position_y: 5, description: 'lah Blah'},
  {number: 41, name: 'Niobium', shortname: 'Nb', weight: 92.90628, moe: 2, row_position_x: 5, row_position_y: 5, description: 'lah Blah'},
  {number: 42, name: 'Molybdenum', shortname: 'Mo', weight: 95.96, moe: 2, row_position_x: 6, row_position_y: 5, description: 'lah Blah'},
  {number: 43, name: 'Technetium', shortname: 'Tc', weight: 98, moe: nil, row_position_x: 7, row_position_y: 5, description: 'lah Blah'},
  {number: 44, name: 'Ruthenium', shortname: 'Ru', weight: 101.07, moe: 2, row_position_x: 8, row_position_y: 5, description: 'lah Blah'},
  {number: 45, name: 'Rhodium', shortname: 'Rh', weight: 102.9055, moe: 2, row_position_x: 9, row_position_y: 5, description: 'lah Blah'},
  {number: 46, name: 'Palladium', shortname: 'Pd', weight: 106.42, moe: 1, row_position_x: 10, row_position_y: 5, description: 'lah Blah'},
  {number: 47, name: 'Silver', shortname: 'Ag', weight: 107.8682, moe: 2, row_position_x: 11, row_position_y: 5, description: 'lah Blah'},
  {number: 48, name: 'Cadmium', shortname: 'Cd', weight: 112.411, moe: 8, row_position_x: 12, row_position_y: 5, description: 'lah Blah'},
  {number: 49, name: 'Indium', shortname: 'In', weight: 114.818, moe: 3, row_position_x: 13, row_position_y: 5, description: 'lah Blah'},
  {number: 50, name: 'Tin', shortname: 'Sn', weight: 118.71, moe: 7, row_position_x: 14, row_position_y: 5, description: 'lah Blah'},
  {number: 51, name: 'Antimony', shortname: 'Sb', weight: 121.76, moe: 1, row_position_x: 15, row_position_y: 5, description: 'lah Blah'},
  {number: 52, name: 'Tellurium', shortname: 'Te', weight: 127.6, moe: 3, row_position_x: 16, row_position_y: 5, description: 'lah Blah'},
  {number: 53, name: 'Iodine', shortname: 'I', weight: 126.90447, moe: 3, row_position_x: 17, row_position_y: 5, description: 'lah Blah'},
  {number: 54, name: 'Xenon', shortname: 'Xe', weight: 131.293, moe: 6, row_position_x: 18, row_position_y: 5, description: 'lah Blah'},
  {number: 55, name: 'Caesium', shortname: 'Cs', weight: 132.9054519,  moe: 2,row_position_x: 1, row_position_y: 6, description: 'lah Blah'},
  {number: 56, name: 'Barium', shortname: 'Ba', weight: 132.9054, moe: 7, row_position_x: 2, row_position_y: 6, description: 'lah Blah'},
  {number: 57, name: 'Lanthanum', shortname: 'La', weight: 138.90547, moe: 7, row_position_x: 4, row_position_y: 9, description: 'lah Blah'},
  {number: 58, name: 'Cerium', shortname: 'Ce', weight: 140.116, moe: 1, row_position_x: 5, row_position_y: 9, description: 'lah Blah'},
  {number: 59, name: 'Praseodymium', shortname: 'Pr', weight: 140.90765, moe: 2, row_position_x: 6, row_position_y: 9, description: 'lah Blah'},
  {number: 60, name: 'Neodymium', shortname: 'Nd', weight: 144.242, moe: 3, row_position_x: 7, row_position_y: 9, description: 'lah Blah'},
  {number: 61, name: 'Promethium', shortname: 'Pm', weight: 145, moe: nil, row_position_x: 8, row_position_y: 9, description: 'lah Blah'},
  {number: 62, name: 'Samarium', shortname: 'Sm', weight: 150.36, moe: 2, row_position_x: 9, row_position_y: 9, description: 'lah Blah'},
  {number: 63, name: 'Europium', shortname: 'Eu', weight: 151.964, moe: 1, row_position_x: 10, row_position_y: 9, description: 'lah Blah'},
  {number: 64, name: 'Gadolinium', shortname: 'Gd', weight: 157.25, moe: 3, row_position_x: 11, row_position_y: 9, description: 'lah Blah'},
  {number: 65, name: 'Terbium', shortname: 'Tb', weight: 158.92535, moe: 2, row_position_x: 12, row_position_y: 9, description: 'lah Blah'},
  {number: 66, name: 'Dysprosium', shortname: 'Dy', weight: 162.5, moe: 1, row_position_x: 13, row_position_y: 9, description: 'lah Blah'},
  {number: 67, name: 'Holmium', shortname: 'Ho', weight: 164.93032, moe: 2, row_position_x: 14, row_position_y: 9, description: 'lah Blah'},
  {number: 68, name: 'Erbium', shortname: 'Er', weight: 167.259, moe: 3, row_position_x: 15, row_position_y: 9, description: 'lah Blah'},
  {number: 69, name: 'Thulium', shortname: 'Tm', weight: 168.93421, moe: 2, row_position_x: 16, row_position_y: 9, description: 'lah Blah'},
  {number: 70, name: 'Ytterbium', shortname: 'Yb', weight: 173.054, moe: 3, row_position_x: 17, row_position_y: 9, description: 'lah Blah'},
  {number: 71, name: 'Lutetium', shortname: 'Lu', weight: 174.9668, moe: 1, row_position_x: 18, row_position_y: 9, description: 'lah Blah'},
  {number: 72, name: 'Hafnium', shortname: 'Hf', weight: 178.49, moe: 2, row_position_x: 4, row_position_y: 6, description: 'lah Blah'},
  {number: 73, name: 'Tantalum', shortname: 'Ta', weight: 180.94788, moe: 2, row_position_x: 5, row_position_y: 6, description: 'lah Blah'},
  {number: 74, name: 'Tungsten', shortname: 'W', weight: 183.84, moe: 1, row_position_x: 6, row_position_y: 6, description: 'lah Blah'},
  {number: 75, name: 'Rhenium', shortname: 'Re', weight: 186.207, moe: 1, row_position_x: 7, row_position_y: 6, description: 'lah Blah'},
  {number: 76, name: 'Osmium', shortname: 'Os', weight: 190.23, moe: 3, row_position_x: 8, row_position_y: 6, description: 'lah Blah'},
  {number: 77, name: 'Iridium', shortname: 'Ir', weight: 192.217, moe: 3, row_position_x: 9, row_position_y: 6, description: 'lah Blah'},
  {number: 78, name: 'Platinum', shortname: 'Pt', weight: 195.084, moe: 9, row_position_x: 10, row_position_y: 6, description: 'lah Blah'},
  {number: 79, name: 'Gold', shortname: 'Au', weight: 196.966569, moe: 4, row_position_x: 11, row_position_y: 6, description: 'lah Blah'},
  {number: 80, name: 'Mercury', shortname: 'Hg', weight: 200.59, moe: 2, row_position_x: 12, row_position_y: 6, description: 'lah Blah'},
  {number: 81, name: 'Thallium', shortname: 'Tl', weight: 204.3833, moe: 2, row_position_x: 13, row_position_y: 6, description: 'lah Blah'},
  {number: 82, name: 'Lead', shortname: 'Pb', weight: 207.2, moe: 1, row_position_x: 14, row_position_y: 6, description: 'lah Blah'},
  {number: 83, name: 'Bismuth', shortname: 'Bi', weight: 208.9804, moe: 1, row_position_x: 15, row_position_y: 6, description: 'lah Blah'},
  {number: 84, name: 'Polonium', shortname: 'Po', weight: 209, moe: nil, row_position_x: 16, row_position_y: 6, description: 'lah Blah'},
  {number: 85, name: 'Astatine', shortname: 'At', weight: 210, moe: nil, row_position_x: 17, row_position_y: 6, description: 'lah Blah'},
  {number: 86, name: 'Radon', shortname: 'Rn', weight: 222, moe: nil, row_position_x: 18, row_position_y: 6, description: 'lah Blah'},
  {number: 87, name: 'Francium', shortname: 'Fr', weight: 223, row_position_x: 1, row_position_y: 7, description: 'lah Blah'},
  {number: 88, name: 'Radium', shortname: 'Ra', weight: 226, row_position_x: 2, row_position_y: 7, description: 'lah Blah'},
  {number: 89, name: 'Actinium', shortname: 'Ac', weight: 227, row_position_x: 4, row_position_y: 10, description: 'lah Blah'},
  {number: 90, name: 'Thorium', shortname: 'Th', weight: 232.03806, moe: 1, row_position_x: 5, row_position_y: 10, description: 'lah Blah'},
  {number: 91, name: 'Protactinium', shortname: 'Pa', weight: 231.0588, moe: 1, row_position_x: 6, row_position_y: 10, description: 'lah Blah'},
  {number: 92, name: 'Uranium', shortname: 'U', weight: 238.02891, moe: 3, row_position_x: 7, row_position_y: 10, description: 'lah Blah'},
  {number: 93, name: 'Neptunium', shortname: 'Np', weight: 237, row_position_x: 8, row_position_y: 10, description: 'lah Blah'},
  {number: 94, name: 'Plutonium', shortname: 'Pu', weight: 244, row_position_x: 9, row_position_y: 10, description: 'lah Blah'},
  {number: 95, name: 'Americium', shortname: 'Am', weight: 243, row_position_x: 10, row_position_y: 10, description: 'lah Blah'},
  {number: 96, name: 'Curium', shortname: 'Cm', weight: 247, row_position_x: 11, row_position_y: 10, description: 'lah Blah'},
  {number: 97, name: 'Berkelium', shortname: 'Bk', weight: 247, row_position_x: 12, row_position_y: 10, description: 'lah Blah'},
  {number: 98, name: 'Californium', shortname: 'Cf', weight: 251, row_position_x: 13, row_position_y: 10, description: 'lah Blah'},
  {number: 99, name: 'Einstenium', shortname: 'Es', weight: 252, row_position_x: 14, row_position_y: 10, description: 'lah Blah'},
  {number: 100, name: 'Fermium', shortname: 'Fm', weight: 257, row_position_x: 15, row_position_y: 10, description: 'lah Blah'},
  {number: 101, name: 'Mendelevium', shortname: 'Md', weight: 258, row_position_x: 16, row_position_y: 10, description: 'lah Blah'},
  {number: 102, name: 'Nobelium', shortname: 'No', weight: 259, row_position_x: 17, row_position_y: 10, description: 'lah Blah'},
  {number: 103, name: 'Lawrencium', shortname: 'Lr', weight: 262, row_position_x: 18, row_position_y: 10, description: 'lah Blah'},
  {number: 104, name: 'Rutherfordium', shortname: 'Rf', weight: 267, row_position_x: 4, row_position_y: 7, description: 'lah Blah'},
  {number: 105, name: 'Dubnium', shortname: 'Db', weight: 268, row_position_x: 5, row_position_y: 7, description: 'lah Blah'},
  {number: 106, name: 'Seaborgium', shortname: 'Sg', weight: 271, row_position_x: 6, row_position_y: 7, description: 'lah Blah'},
  {number: 107, name: 'Bohrium', shortname: 'Bh', weight: 272, row_position_x: 7, row_position_y: 7, description: 'lah Blah'},
  {number: 108, name: 'Hassium', shortname: 'Hs', weight: 270, row_position_x: 8, row_position_y: 7, description: 'lah Blah'},
  {number: 109, name: 'Meitnerium', shortname: 'Mt', weight: 276, row_position_x: 9, row_position_y: 7, description: 'lah Blah'},
  {number: 110, name: 'Darmstadium', shortname: 'Ds', weight: 281, row_position_x: 10, row_position_y: 7, description: 'lah Blah'},
  {number: 111, name: 'Roentgenium', shortname: 'Rg', weight: 280, row_position_x: 11, row_position_y: 7, description: 'lah Blah'},
  {number: 112, name: 'Copernicium', shortname: 'Cn', weight: 285, row_position_x: 12, row_position_y: 7, description: 'lah Blah'},
  {number: 113, name: 'Unutrium', shortname: 'Uut', weight: 284, row_position_x: 13, row_position_y: 7, description: 'lah Blah'},
  {number: 114, name: 'Flerovium', shortname: 'Fl', weight: 289, row_position_x: 14, row_position_y: 7, description: 'lah Blah'},
  {number: 115, name: 'Ununpentium', shortname: 'Uup', weight: 288, row_position_x: 15, row_position_y: 7, description: 'lah Blah'},
  {number: 116, name: 'Livermorium', shortname: 'Lv', weight: 293, row_position_x: 16, row_position_y: 7, description: 'lah Blah'},
  {number: 117, name: 'Ununseptium', shortname: 'Uus', weight: 294, row_position_x: 17, row_position_y: 7, description: 'lah Blah'},
  {number: 118, name: 'Ununoctium', shortname: 'Uuo', weight: 294, row_position_x: 18, row_position_y: 7, description: 'lah Blah'}
  ])

#anything over 101 has no MOE